[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
citizen_registry = "Ckghe1MiBJEX9DLHHMqtXaczXQyCNHrimq9GixjFiyE6"
contract_registry = "GGtDAGtHMRd6BxDGyoSXXVfevDDjhj8XnTnAYftnGmBU"
crowdfunding = "G11sZPjAuksZ417dWH2zysKwr1p6XjNAaonUtqveDPSd"
district_treasury = "44SAVcK4BVrKQvX1WAgHPCcov1vBnNpMWhFbVJCziGwy"
jury_mechanism = "F2wfSrALyt3qqUrV7pP2XqCm6mLN8rPLQ5UDTXz3C68w"
penalty_engine = "DBMPFjrt7aaiCh4s56wrsge2uMcu8zn9Wb7o6LE28E7z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/amanat.test.ts"
