[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
citizen_registry = "2Gjs7gsyaBayR38AACScCPz3ZgRf3JZvAoW63A5jKCd3"
contract_registry = "6E9SJu8QPEAoyuZRh9SBhVMtkYypFmgYsHFbJb792pz4"
district_treasury = "HtBdghVoWexYkmmpUaCc2NrpU2YQTSytyhvtSL4QCQdJ"
jury_mechanism = "HVZcSwtwNA2eJwEgimoDFTXe74pmGpvv1CDUXaEntzTd"
penalty_engine = "9xYTKtPkMDJdVqm56f5ttx5XUgQU5S4nBLT3WHoSZxeT"
crowdfunding = "3vCqBvYEnXb1kW9CB4smrAMUzSrdTFfFv2XuMGw1Sdzj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx tests/amanat.test.ts"
