[package]
name = "jury-mechanism"
version = "0.1.0"
description = "Amanat Protocol — Jury Mechanism (Commit-Reveal Voting)"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "jury_mechanism"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
idl-build = ["anchor-lang/idl-build"]

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
solana-sha256-hasher = "2"
